// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3o-QjcypoBFOtuTkmhUr3_yauYUGo0Kg',
    appId: '1:73786649304:web:4d3bc4c0c4dfc23f3105ad',
    messagingSenderId: '73786649304',
    projectId: 'btlchuyende2',
    authDomain: 'btlchuyende2.firebaseapp.com',
    storageBucket: 'btlchuyende2.firebasestorage.app',
    measurementId: 'G-E5VSHVWXH8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApzWBh-sGHS1b2j0dLWM0pwhNM9DJj3Qw',
    appId: '1:73786649304:android:fb4b81aa7556ea4a3105ad',
    messagingSenderId: '73786649304',
    projectId: 'btlchuyende2',
    storageBucket: 'btlchuyende2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5RsTnKnDgSHP3SD7i3yKCx_RafzdkWc4',
    appId: '1:73786649304:ios:8f5d85c9292a14e53105ad',
    messagingSenderId: '73786649304',
    projectId: 'btlchuyende2',
    storageBucket: 'btlchuyende2.firebasestorage.app',
    iosBundleId: 'com.example.shoeStoreApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3o-QjcypoBFOtuTkmhUr3_yauYUGo0Kg',
    appId: '1:73786649304:web:a144f9970a68cd293105ad',
    messagingSenderId: '73786649304',
    projectId: 'btlchuyende2',
    authDomain: 'btlchuyende2.firebaseapp.com',
    storageBucket: 'btlchuyende2.firebasestorage.app',
    measurementId: 'G-LG3W70Z4KB',
  );
}
